from jsonmodels import models, fields, errors, validators

class Date(models.Base):
    expression = fields.StringField(required=True)
    begin = fields.StringField(required=True)
    end = fields.StringField()
    date_type = fields.StringField()

class Extent(models.Base):
    number = fields.StringField(required=True)
    unit = fields.StringField(required=True)

class Container(models.Base):
    top_container = fields.StringField()
    top_container_indicator = fields.StringField()
    sub_container = fields.StringField()
    sub_container_indicator = fields.StringField()
    sub_sub_container = fields.StringField()
    sub_sub_container_indicator = fields.StringField()

class Component(models.Base):
    id = fields.StringField(required=True)
    collection_id = fields.StringField(required=True)
    title = fields.StringField(required=True)
    title_filing_si = fields.StringField()
    repository = fields.StringField(required=True)
    level = fields.StringField(required=True)
    collection_name = fields.StringField(required=True)
    dates = fields.ListField(Date)
    extents = fields.ListField(Extent)
    languages = fields.ListField(str)
    creators = fields.ListField(str)
    names = fields.ListField(str)
    subjects = fields.ListField(str)
    places = fields.ListField(str)
    abstract = fields.ListField(str)
    accessrestrict = fields.ListField(str)
    scopecontent = fields.ListField(str)
    accruals = fields.ListField(str)
    altformavail = fields.ListField(str)
    appraisal = fields.ListField(str)
    arrangement = fields.ListField(str)
    bibliography = fields.ListField(str)
    bioghist = fields.ListField(str)
    custodhist = fields.ListField(str)
    fileplan = fields.ListField(str)
    note = fields.ListField(str)
    odd = fields.ListField(str)
    originalsloc = fields.ListField(str)
    otherfindaid = fields.ListField(str)
    phystech = fields.ListField(str)
    prefercite = fields.ListField(str)
    processinfo = fields.ListField(str)
    relatedmaterial = fields.ListField(str)
    separatedmaterial = fields.ListField(str)
    userestrict = fields.ListField(str)
    materialspec = fields.ListField(str)
    physloc = fields.ListField(str)

    containers = fields.ListField(Container)
    has_digital_object = fields.StringField()
    components = fields.ListField()
        


class SolrCollection(models.Base):
    id = fields.StringField(required=True)
    unitid_ssm = fields.ListField(str)
    title_ssm = fields.ListField(str)
    #title_teim = fields.ListField(str)
    unitdate_ssm = fields.ListField(str)
    #unitdate_bulk_ssim
    #unitdate_inclusive_ssm
    #unitdate_other_ssim
    date_range_sim = fields.ListField(int)
    extent_ssm = fields.ListField(str)
    language_ssm = fields.ListField(str)
    abstract_ssm = fields.ListField(str)
    collection_ssm = fields.ListField(str)
    collection_sim = fields.ListField(str)
    collection_ssi = fields.ListField(str)
    #collection_title_tesim
    accessrestrict_ssm = fields.ListField(str)
    scopecontent_ssm = fields.ListField(str)
    repository_ssm = fields.ListField(str)
    repository_sim = fields.ListField(str)
    ead_ssi = fields.ListField(str)
    level_ssm = fields.ListField(str)
    level_sim = fields.ListField(str)
    creator_ssm = fields.ListField(str)
    creator_ssim = fields.ListField(str)
    creators_ssim = fields.ListField(str)
    has_online_content_ssm = fields.ListField(str)
    normalized_title_ssm = fields.ListField(str)
    normalized_date_ssm = fields.ListField(str)
    names_coll_ssim = fields.ListField(str)
    names_ssim = fields.ListField(str)
    access_subjects_ssim = fields.ListField(str)
    access_subjects_ssm = fields.ListField(str)
    geogname_ssm = fields.ListField(str)
    geogname_sim = fields.ListField(str)
    places_sim = fields.ListField(str)
    places_ssim = fields.ListField(str)
    places_ssm = fields.ListField(str)
    accruals_ssm = fields.ListField(str)
    altformavail_ssm = fields.ListField(str)
    appraisal_ssm = fields.ListField(str)
    arrangement_ssm = fields.ListField(str)
    bibliography_ssm = fields.ListField(str)
    bioghist_ssm = fields.ListField(str)
    custodhist_ssm = fields.ListField(str)
    fileplan_ssm = fields.ListField(str)
    note_ssm = fields.ListField(str)
    odd_ssm = fields.ListField(str)
    originalsloc_ssm = fields.ListField(str)
    otherfindaid_ssm = fields.ListField(str)
    phystech_ssm = fields.ListField(str)
    prefercite_ssm = fields.ListField(str)
    processinfo_ssm = fields.ListField(str)
    relatedmaterial_ssm = fields.ListField(str)
    separatedmaterial_ssm = fields.ListField(str)
    userestrict_ssm = fields.ListField(str)
    materialspec_ssm = fields.ListField(str)
    physloc_ssm = fields.ListField(str)
    containers_ssim = fields.ListField(str)
    _childDocuments_ = fields.ListField()
    

class SolrComponent(SolrCollection):
    parent_ssim = fields.ListField(str)
    parent_ssm = fields.ListField(str)
    parent_ssi = fields.ListField(str)
    parent_unittitles_ssm = fields.ListField(str)
    component_level_isim = fields.ListField(int)
    collection_unitid_ssm = fields.ListField(str)
    child_component_count_isim = fields.ListField(int)
    parent_access_restrict_ssm = fields.ListField(str)
    parent_access_terms_ssm = fields.ListField(str)
    title_filing_si = fields.StringField()
    ref_ssm = fields.ListField(str)